### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by ezequieltejada** [ben-eb/gulp-uncss#38]
Hi! I just install gulp-uncss and when I added to my task, I get the following error

```
[21:00:21] Starting 'styles'...
execvp(): Permission denied
[21:00:27] { name: 'Error',
  message: 'execvp(): Permission denied\n',
  stack: 'Error: execvp(): Permission denied\n\n    at Socket.onStderr (/var/www/public/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/spawn.js:79:28)\n    at Socket.EventEmitter.emit (events.js:117:20)\n    at Socket.<anonymous> (_stream_readable.js:746:14)\n    at Socket.EventEmitter.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:408:10)\n    at emitReadable (_stream_readable.js:404:5)\n    at readableAddChunk (_stream_readable.js:165:9)\n    at Socket.Readable.push (_stream_readable.js:127:10)\n    at Pipe.onread (net.js:526:21)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uncss' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

The folder structure is quite simple:

gulpfile
app
   |
   --> index.html
   --> styles
             |
              -->styles.css

And this is the task:

```
gulp.task('styles', function () {
    return gulp.src('app/sass/**/*.scss')
        .pipe($.sass({
            errLogToConsole: true,
            includePaths: ['styles'].concat(neat)
        }).on('error', errorHandler))
        .pipe($.autoprefixer('last 1 version'))
        .pipe($.concat('styles.css'))
        .pipe($.uncss({
            html: 'app/index.html'
        }).on('error', $.util.log))
        .pipe(gulp.dest('app/styles'))
        .pipe(reload({stream:true}));
});
```

Thanks!

**Comment by ben-eb** [comment]
I think it's related to the PhantomJS installation. Can you try downloading it manually? More info:

https://github.com/sindresorhus/pageres/issues/54#issuecomment-36102649

**Comment by ezequieltejada** [comment]
Thanks for the quick response Ben!

I followed these [steps](http://www.joyceleong.com/log/installing-phantomjs-on-ubuntu/) then I checked the version with ```phantomjs --version``` I got 1.7.0 but I still get the same error.

**Comment by ben-eb** [comment]
It might be a permissions issue. Try setting execute permissions on the file from which the error was thrown.

**Comment by ben-eb** [comment]
Closing due to inactivity.
