### ISSUE TITLE
JS error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Thomasdezeeuw** [ben-eb/gulp-uncss#40]
Running the following code with version 1.0.4 of uncss and 3.9.0 of Gulp.

```js
var gulp = require('gulp')
	, uncss = require('gulp-uncss')

	gulp.src(paths.src.style)
		.pipe(concat('style.css'))
		.pipe(uncss({
			html: ['./public/**/*.html']
		}))
		.pipe(gulp.dest(paths.dst.style))
```

Stacktrace:

```
/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
TypeError: Cannot read property 'map' of undefined
    at getHTML (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:28:28)
    at /Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:221:20
    at /Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/using.js:165:30
    at tryCatcher (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

Maybe I should report this issue at uncss repo?

**Comment by ben-eb** [comment]
Yeah the issue is likely with UnCSS, but check that your paths are correct. Looks like no HTML files are being passed through to the module.

**Comment by Thomasdezeeuw** [comment]
Created the issue: https://github.com/giakki/uncss/issues/201.

The paths are correct, I use them in other stuff as well.
