### ISSUE TITLE
Error: Cannot Load

### ISSUE THREAD

**Issue by adamdilibero** [ben-eb/gulp-uncss#41]
/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
Error: Cannot load http://sx-ecommerce-sx-adl.local.thisisblaze.com/blog/039-wash-off-039-fake-tan: Phantomjs returned status fail
    at reject (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/phridge/lib/phantom/start.js:71)
    at onPageLoaded (:4)
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/phridge/lib/Phantom.js:165:20)
    at Page.run (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/phridge/lib/Page.js:62:25)
    at Phantom.openPage (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/phridge/lib/Phantom.js:123:17)
    at Object.fromRemote (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/uncss/src/phantom.js:148:20)
    at /usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:41:28
    at tryCatcher (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/usr/home/apache/hosts/WSBprojects/SX-Ecommerce/node_modules/gulp-uncss/node_modules/bluebird/js/main/map.js:29:23)

Hi, 

I think this issue is perhaps upstream either in PhantomJS or uncss itself not really sure, I'm passing in an array of urls from a sitemap and these links are failing, but if I instead pass in just the failed url on its own as an individual url it works just fine.. Any suggestions?

**Comment by ben-eb** [comment]
Not sure the exact problem but yeah, either in UnCSS or Phantom. This module doesn't provide much functionality other than converting a stream into options for UnCSS.

Perhaps this is related? http://stackoverflow.com/questions/24473169/phantomjs-certain-pages-failing-to-open
