### ISSUE TITLE
Getting PhantomJS: Cannot open about:blank error

### ISSUE THREAD

**Issue by prabhg** [ben-eb/gulp-uncss#49]
When I am trying to run gulp-uncss I am running into error
__Error: PhantomJS: Cannot open about:blank__

A quick google search shows that this was a widely reported uncss issue which was resolved in version 0.13 of uncss. However current gulp-uncss version is still using 0.12.1 version of uncss. Is there any plan to upgrade to latest uncss version in gulp-uncss soon?

Reference: https://github.com/giakki/uncss/issues/150

Stack trace:
```
.../node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
Error: PhantomJS: Cannot open about:blank
    at reject (.../node_modules/gulp-uncss/node_modules/phridge/lib/phantom/start.js:71)
    at :4
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (.../node_modules/gulp-uncss/node_modules/phridge/lib/Phantom.js:165:20)
    at Page.run (.../node_modules/gulp-uncss/node_modules/phridge/lib/Page.js:62:25)
    at .../node_modules/gulp-uncss/node_modules/uncss/src/phantom.js:125:21
    at tryCatchReject (.../node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (.../node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (.../node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (.../node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (.../node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (.../node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by ben-eb** [comment]
`1.0.5` is out with an upgrade to `0.13.0`.
